server:
  port: 8802
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eureka02
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka01:8801/eureka